name: Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.27.x'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        go get .
    - name: Run Unit tests
      run: |
        go test -v -covermode atomic -coverprofile="coverage.out" -coverpkg=./ecs ./...
        go tool cover -func="coverage.out"
    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v5
    #   with:
    #     files: ./coverage.out
    #     token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.27.x'
      - name: Check format
        run: |
          if gofmt -e -l . >&1 | grep '^'; then
            exit 1
          fi
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
